version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: portalchurras-db
    environment:
      POSTGRES_DB: portalchurras
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - portalchurras-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: portalchurras-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - portalchurras-network

  # Redis Cache (para sessões e cache)
  redis:
    image: redis:7-alpine
    container_name: portalchurras-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - portalchurras-network

  # pgAdmin (opcional - interface gráfica para PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: portalchurras-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@portalchurras.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - portalchurras-network

volumes:
  postgres-data:
  rabbitmq-data:
  redis-data:
  pgadmin-data:

networks:
  portalchurras-network:
    driver: bridge